version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
#        image: php:8.2-fpm
        volumes:
            - ${APPVOLUME}:/var/www/html
            - ./php/php.ini:/usr/local/etc/php/php.ini
        networks:
            - app-network
        depends_on:
            - db
            - redis

    db:
        image: postgres:latest
        environment:
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_DATABASE}
        ports:
            - "${BIND_HOST:-}${DB_PORT}:5432"
        volumes:
            - ${DBVOLUME}:/var/lib/postgresql/data
        networks:
            - app-network

    redis:
        image: redis:latest
        ports:
            - "${BIND_HOST:-}${REDIS_PORT}:6379"
        networks:
            - app-network

    nginx:
        image: nginx:latest
        volumes:
            - ${APPVOLUME}:/var/www/html
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "${BIND_HOST:-}${APP_PORT}:80"
        networks:
            - app-network
        depends_on:
            - app

networks:
    app-network:
        driver: bridge
